const ANIMATION = [
  "animation",
  "animation-composition",
  "animation-delay",
  "animation-direction",
  "animation-duration",
  "animation-fill-mode",
  "animation-iteration-count",
  "animation-name",
  "animation-play-state",
  "animation-timing-function",
  "animation-timeline",
];

function isAnimationProperty(property) {
  return ANIMATION.includes(property);
}

const TRANSITION = [
  "transition",
  "transition-delay",
  "transition-duration",
  "transition-property",
  "transition-timing-function",
];

export function isTransitionProperty(property) {
  return TRANSITION.includes(property);
}

export function isAnimationLikeProperty(property) {
  return isAnimationProperty(property) || isTransitionProperty(property);
}

const BACKGROUND = [
  "background",
  "background-attachment",
  "background-blend-mode",
  "background-clip",
  "background-color",
  "background-image",
  "background-origin",
  "background-position",
  "background-position-x",
  "background-position-y",
  "background-repeat",
  "background-size",
  "box-shadow",
  "accent-color",
  "color-scheme",
  "object-fit",
  "object-position",
  "opacity",
];

export function isBackgroundProperty(property) {
  return BACKGROUND.includes(property);
}

const BORDER = [
  "border",
  "border-block",
  "border-block-color",
  "border-block-style",
  "border-block-width",
  "border-block-end",
  "border-block-end-color",
  "border-block-end-style",
  "border-block-end-width",
  "border-block-start",
  "border-block-start-color",
  "border-block-start-style",
  "border-block-start-width",
  "border-bottom",
  "border-bottom-color",
  "border-bottom-left-radius",
  "border-bottom-right-radius",
  "border-bottom-style",
  "border-bottom-width",
  "border-collapse",
  "border-color",
  "border-end-end-radius",
  "border-end-start-radius",
  "border-image",
  "border-image-outset",
  "border-image-repeat",
  "border-image-slice",
  "border-image-source",
  "border-image-width",
  "border-inline",
  "border-inline-end",
  "border-inline-color",
  "border-inline-style",
  "border-inline-width",
  "border-inline-end-color",
  "border-inline-end-style",
  "border-inline-end-width",
  "border-inline-start",
  "border-inline-start-color",
  "border-inline-start-style",
  "border-inline-start-width",
  "border-left",
  "border-left-color",
  "border-left-style",
  "border-left-width",
  "border-radius",
  "border-right",
  "border-right-color",
  "border-right-style",
  "border-right-width",
  "border-spacing",
  "border-start-end-radius",
  "border-start-start-radius",
  "border-style",
  "border-top",
  "border-top-color",
  "border-top-left-radius",
  "border-top-right-radius",
  "border-top-style",
  "border-top-width",
  "border-width",
  "outline",
  "outline-color",
  "outline-offset",
  "outline-style",
  "outline-width",
];

export function isBorderProperty(property) {
  return BORDER.includes(property);
}

export function isBackgroundLikeProperty(property) {
  return isBackgroundProperty(property) || isBorderProperty(property);
}

const FONT = [
  "font",
  "font-family",
  "font-feature-settings",
  "font-kerning",
  "font-language-override",
  "font-optical-sizing",
  "font-variation-settings",
  "font-size",
  "font-size-adjust",
  "font-smooth",
  "font-stretch",
  "font-style",
  "font-synthesis",
  "font-variant",
  "font-variant-alternates",
  "font-variant-caps",
  "font-variant-east-asian",
  "font-variant-ligatures",
  "font-variant-numeric",
  "font-variant-position",
  "font-weight",
  "text-align",
  "text-align-last",
  "text-combine-upright",
  "text-decoration",
  "text-decoration-color",
  "text-decoration-line",
  "text-decoration-skip",
  "text-decoration-skip-ink",
  "text-decoration-style",
  "text-decoration-thickness",
  "text-emphasis",
  "text-emphasis-color",
  "text-emphasis-position",
  "text-emphasis-style",
  "text-indent",
  "text-justify",
  "text-orientation",
  "text-overflow",
  "text-rendering",
  "text-shadow",
  "text-size-adjust",
  "text-transform",
  "text-underline-offset",
  "text-underline-position",
  "glyph-orientation-horizontal",
  "glyph-orientation-vertical",
  "kerning",
  "text-anchor",
  "unicode-range",
  "hyphenate-character",
  "hyphens",
  "letter-spacing",
  "line-break",
  "line-clamp",
  "line-height",
  "line-height-step",
  "white-space",
  "word-break",
  "word-spacing",
  "word-wrap",
  "max-lines",
  "color",
];

export function isFontProperty(property) {
  return FONT.includes(property);
}

const LAYOUT = [
  "margin",
  "margin-block",
  "margin-block-end",
  "margin-block-start",
  "margin-bottom",
  "margin-inline",
  "margin-inline-end",
  "margin-inline-start",
  "margin-left",
  "margin-right",
  "margin-top",
  "margin-trim",
  "padding",
  "padding-block",
  "padding-block-end",
  "padding-block-start",
  "padding-bottom",
  "padding-inline",
  "padding-inline-end",
  "padding-inline-start",
  "padding-left",
  "padding-right",
  "padding-top",
  "translate",
  "min-block-size",
  "min-inline-size",
  "justify-self",
  "align-self",
  "float",
  "max-inline-size",
  "place-self",
];

export function isLayoutProperty(property) {
  return LAYOUT.includes(property);
}

const SIZE = [
  "max-width",
  "min-height",
  "min-width",
  "aspect-ratio",
  "height",
  "max-height",
  "width",
  "rotate",
  "scale",
];

export function isSizeProperty(property) {
  return SIZE.includes(property);
}

export function isLayoutLikeProperty(property) {
  return isLayoutProperty(property) || isSizeProperty(property);
}

const MISC = [
  "voice-balance",
  "voice-duration",
  "voice-family",
  "voice-pitch",
  "voice-range",
  "voice-rate",
  "voice-stress",
  "voice-volume",
  "marker",
  "marker-end",
  "marker-mid",
  "marker-start",
  "pause",
  "pause-after",
  "pause-before",
  "rest",
  "rest-after",
  "rest-before",
  "shape-rendering",
  "src",
  "speak",
  "speak-as",
  "baseline-shift",
  "behavior",
  "clip-rule",
  "cue",
  "cue-after",
  "cue-before",
  "scrollbar-color",
  "scrollbar-gutter",
  "scrollbar-width",
  "scroll-behavior",
  "scroll-margin",
  "scroll-margin-block",
  "scroll-margin-block-start",
  "scroll-margin-block-end",
  "scroll-margin-bottom",
  "scroll-margin-inline",
  "scroll-margin-inline-start",
  "scroll-margin-inline-end",
  "scroll-margin-left",
  "scroll-margin-right",
  "scroll-margin-top",
  "scroll-padding",
  "scroll-padding-block",
  "scroll-padding-block-start",
  "scroll-padding-block-end",
  "scroll-padding-bottom",
  "scroll-padding-inline",
  "scroll-padding-inline-start",
  "scroll-padding-inline-end",
  "scroll-padding-left",
  "scroll-padding-right",
  "scroll-padding-top",
  "scroll-snap-align",
  "scroll-snap-coordinate",
  "scroll-snap-destination",
  "scroll-snap-points-x",
  "scroll-snap-points-y",
  "scroll-snap-stop",
  "scroll-snap-type",
  "scroll-snap-type-x",
  "scroll-snap-type-y",
  "scroll-timeline",
  "scroll-timeline-axis",
  "scroll-timeline-name",
  "overflow",
  "overflow-anchor",
  "overflow-block",
  "overflow-clip-box",
  "overflow-clip-margin",
  "overflow-inline",
  "overflow-wrap",
  "overflow-x",
  "overflow-y",
  "overscroll-behavior",
  "overscroll-behavior-block",
  "overscroll-behavior-inline",
  "overscroll-behavior-x",
  "overscroll-behavior-y",
  "list-style",
  "list-style-image",
  "list-style-position",
  "list-style-type",
  "mask",
  "mask-border",
  "mask-border-mode",
  "mask-border-outset",
  "mask-border-repeat",
  "mask-border-slice",
  "mask-border-source",
  "mask-border-width",
  "mask-clip",
  "mask-composite",
  "mask-image",
  "mask-mode",
  "mask-origin",
  "mask-position",
  "mask-repeat",
  "mask-size",
  "mask-type",
  "masonry-auto-flow",
  "math-depth",
  "math-shift",
  "math-style",
  "image-orientation",
  "image-rendering",
  "image-resolution",
  "ime-mode",
  "initial-letter",
  "initial-letter-align",
  "inline-size",
  "input-security",
  "isolation",
  "contain",
  "contain-intrinsic-size",
  "contain-intrinsic-block-size",
  "contain-intrinsic-height",
  "contain-intrinsic-inline-size",
  "contain-intrinsic-width",
  "content",
  "content-visibility",
  "counter-increment",
  "counter-reset",
  "counter-set",
  "cursor",
  "direction",
  "break-after",
  "break-before",
  "break-inside",
  "caption-side",
  "caret",
  "caret-color",
  "caret-shape",
  "clear",
  "clip",
  "clip-path",
  "all",
  "appearance",
  "azimuth",
  "backdrop-filter",
  "backface-visibility",
  "block-overflow",
  "offset",
  "offset-anchor",
  "offset-distance",
  "offset-path",
  "offset-position",
  "offset-rotate",
  "orphans",
  "page-break-after",
  "page-break-before",
  "page-break-inside",
  "paint-order",
  "perspective",
  "perspective-origin",
  "pointer-events",
  "quotes",
  "resize",
  "ruby-align",
  "ruby-merge",
  "ruby-position",
  "shape-image-threshold",
  "shape-margin",
  "shape-outside",
  "tab-size",
  "touch-action",
  "user-select",
  "widows",
  "will-change",
  "writing-mode",
  "z-index",
  "zoom",
  "alignment-baseline",
  "dominant-baseline",
  "print-color-adjust",
  "empty-cells",
  "filter",
  "forced-color-adjust",
  "hanging-punctuation",
  "unicode-bidi",
  "box-sizing",
  "transform",
  "transform-box",
  "transform-origin",
  "transform-style",
  "grid-template",
  "align-tracks",
  "block-size",
  "max-block-size",
  "mix-blend-mode",
  "order",
  "visibility",
];

export function isMiscProperty(property) {
  return MISC.includes(property);
}

const POSITION = [
  "position",
  "inset",
  "inset-block",
  "inset-block-end",
  "inset-block-start",
  "inset-inline",
  "inset-inline-end",
  "inset-inline-start",
  "left",
  "right",
  "top",
  "bottom",
];

export function isPositionProperty(property) {
  return POSITION.includes(property);
}

const DISPLAY = [
  "align-items",
  "box-align",
  "box-decoration-break",
  "box-direction",
  "box-flex",
  "box-flex-group",
  "box-lines",
  "box-ordinal-group",
  "box-orient",
  "box-pack",
  "display",
  "flex",
  "flex-basis",
  "flex-direction",
  "flex-flow",
  "flex-grow",
  "flex-shrink",
  "flex-wrap",
  "gap",
  "grid",
  "grid-area",
  "grid-auto-columns",
  "grid-auto-flow",
  "grid-auto-rows",
  "grid-column",
  "grid-column-end",
  "grid-column-gap",
  "grid-column-start",
  "grid-gap",
  "grid-row",
  "grid-row-end",
  "grid-row-gap",
  "grid-row-start",
  "grid-template-areas",
  "grid-template-columns",
  "grid-template-rows",
  "justify-content",
  "justify-items",
  "justify-tracks",
  "place-content",
  "place-items",
  "row-gap",
  "table-layout",
  "column-count",
  "column-fill",
  "column-gap",
  "column-rule",
  "column-rule-color",
  "column-rule-style",
  "column-rule-width",
  "column-span",
  "column-width",
  "columns",
  "align-content",
  "vertical-align",
];

export function isDisplayProperty(property) {
  return DISPLAY.includes(property);
}

export function isPositionLikeProperty(property) {
  return isDisplayProperty(property) || isPositionProperty(property);
}

const PREFIXED = [
  "--*",
  "-ms-accelerator",
  "-ms-block-progression",
  "-ms-content-zoom-chaining",
  "-ms-content-zooming",
  "-ms-content-zoom-limit",
  "-ms-content-zoom-limit-max",
  "-ms-content-zoom-limit-min",
  "-ms-content-zoom-snap",
  "-ms-content-zoom-snap-points",
  "-ms-content-zoom-snap-type",
  "-ms-filter",
  "-ms-flow-from",
  "-ms-flow-into",
  "-ms-grid-columns",
  "-ms-grid-rows",
  "-ms-high-contrast-adjust",
  "-ms-hyphenate-limit-chars",
  "-ms-hyphenate-limit-lines",
  "-ms-hyphenate-limit-zone",
  "-ms-ime-align",
  "-ms-overflow-style",
  "-ms-scrollbar-3dlight-color",
  "-ms-scrollbar-arrow-color",
  "-ms-scrollbar-base-color",
  "-ms-scrollbar-darkshadow-color",
  "-ms-scrollbar-face-color",
  "-ms-scrollbar-highlight-color",
  "-ms-scrollbar-shadow-color",
  "-ms-scrollbar-track-color",
  "-ms-scroll-chaining",
  "-ms-scroll-limit",
  "-ms-scroll-limit-x-max",
  "-ms-scroll-limit-x-min",
  "-ms-scroll-limit-y-max",
  "-ms-scroll-limit-y-min",
  "-ms-scroll-rails",
  "-ms-scroll-snap-points-x",
  "-ms-scroll-snap-points-y",
  "-ms-scroll-snap-type",
  "-ms-scroll-snap-x",
  "-ms-scroll-snap-y",
  "-ms-scroll-translation",
  "-ms-text-autospace",
  "-ms-touch-select",
  "-ms-user-select",
  "-ms-wrap-flow",
  "-ms-wrap-margin",
  "-ms-wrap-through",
  "-moz-appearance",
  "-moz-binding",
  "-moz-border-bottom-colors",
  "-moz-border-left-colors",
  "-moz-border-right-colors",
  "-moz-border-top-colors",
  "-moz-context-properties",
  "-moz-float-edge",
  "-moz-force-broken-image-icon",
  "-moz-image-region",
  "-moz-orient",
  "-moz-outline-radius",
  "-moz-outline-radius-bottomleft",
  "-moz-outline-radius-bottomright",
  "-moz-outline-radius-topleft",
  "-moz-outline-radius-topright",
  "-moz-stack-sizing",
  "-moz-text-blink",
  "-moz-user-focus",
  "-moz-user-input",
  "-moz-user-modify",
  "-moz-window-dragging",
  "-moz-window-shadow",
  "-webkit-appearance",
  "-webkit-border-before",
  "-webkit-border-before-color",
  "-webkit-border-before-style",
  "-webkit-border-before-width",
  "-webkit-box-reflect",
  "-webkit-line-clamp",
  "-webkit-mask",
  "-webkit-mask-attachment",
  "-webkit-mask-clip",
  "-webkit-mask-composite",
  "-webkit-mask-image",
  "-webkit-mask-origin",
  "-webkit-mask-position",
  "-webkit-mask-position-x",
  "-webkit-mask-position-y",
  "-webkit-mask-repeat",
  "-webkit-mask-repeat-x",
  "-webkit-mask-repeat-y",
  "-webkit-mask-size",
  "-webkit-overflow-scrolling",
  "-webkit-tap-highlight-color",
  "-webkit-text-fill-color",
  "-webkit-text-stroke",
  "-webkit-text-stroke-color",
  "-webkit-text-stroke-width",
  "-webkit-touch-callout",
  "-webkit-user-modify",
  "-moz-background-clip",
  "-moz-border-radius-bottomleft",
  "-moz-border-radius-bottomright",
  "-moz-border-radius-topleft",
  "-moz-border-radius-topright",
  "-moz-control-character-visibility",
  "-moz-osx-font-smoothing",
  "-moz-user-select",
  "-ms-flex-align",
  "-ms-flex-item-align",
  "-ms-flex-line-pack",
  "-ms-flex-negative",
  "-ms-flex-pack",
  "-ms-flex-order",
  "-ms-flex-positive",
  "-ms-flex-preferred-size",
  "-ms-interpolation-mode",
  "-ms-grid-column-align",
  "-ms-grid-row-align",
  "-ms-hyphenate-limit-last",
  "-webkit-background-clip",
  "-webkit-column-break-after",
  "-webkit-column-break-before",
  "-webkit-column-break-inside",
  "-webkit-font-smoothing",
  "-webkit-mask-box-image",
  "-webkit-print-color-adjust",
  "-webkit-text-security",
  "-webkit-user-drag",
  "-webkit-user-select",
];

export function isPrefixedProperty(property) {
  return PREFIXED.includes(property);
}

const SVG = [
  "stroke",
  "stroke-dasharray",
  "stroke-dashoffset",
  "stroke-linecap",
  "stroke-linejoin",
  "stroke-miterlimit",
  "stroke-opacity",
  "stroke-width",
  "fill",
  "fill-opacity",
  "fill-rule",
];

export function isSvgProperty(property) {
  return SVG.includes(property);
}
